apiVersion: v1
kind: Service
metadata:
  name: tracing-api-service
  namespace: default
  labels:
    app: tracing-api
spec:
  selector:
    app: tracing-api
  ports:
  - port: 80
    targetPort: 8000
    protocol: TCP
  type: ClusterIP